# Generated by Django 3.0.5 on 2020-11-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201101_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='billing_address_1',
            field=models.CharField(default=1, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='billing_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='billing_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='billing_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='billing_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='billing_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_address_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
