# Generated by Django 3.0.5 on 2020-11-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201101_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='billing_address_1',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
