# Generated by Django 3.0.5 on 2020-11-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201101_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
