# Generated by Django 3.0.5 on 2020-10-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
