# Generated by Django 3.0.5 on 2020-10-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20201018_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0.175, max_digits=9),
        ),
    ]
