# Generated by Django 3.0.5 on 2020-10-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20201018_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
