# Generated by Django 3.0.5 on 2020-11-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_auto_20201101_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_total',
        ),
    ]
