# Generated by Django 3.0.5 on 2020-11-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_auto_20201102_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
