# Generated by Django 3.0.5 on 2020-10-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_ordered_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='ordered_cart',
        ),
    ]
