# Generated by Django 3.0.5 on 2020-10-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_variation_is_active'),
        ('cart', '0003_remove_cartitem_ordered_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(null=True, to='catalog_app.Variation'),
        ),
    ]
