# Generated by Django 3.0.5 on 2020-10-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_variation_is_active'),
        ('cart', '0004_cartitem_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, null=True, to='catalog_app.Variation'),
        ),
    ]
