# Generated by Django 3.0.5 on 2020-10-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_variation_is_active'),
        ('cart', '0005_auto_20201022_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(to='catalog_app.Variation'),
        ),
    ]
